NEUROLOGY_QA = [
    {"question": "What is a migraine?", "answer": "A migraine is a type of headache characterized by intense, throbbing pain, often accompanied by nausea, vomiting, and sensitivity to light or sound."},
    {"question": "What are the symptoms of a stroke?", "answer": "Symptoms of a stroke include sudden numbness or weakness, confusion, trouble speaking, vision problems, dizziness, and loss of balance or coordination."},
    {"question": "What is epilepsy?", "answer": "Epilepsy is a neurological disorder marked by recurrent, unprovoked seizures due to abnormal electrical activity in the brain."},
    {"question": "What causes Parkinson's disease?", "answer": "Parkinson's disease is caused by the degeneration of dopamine-producing neurons in the brain, leading to movement and coordination problems."},
    {"question": "What is multiple sclerosis?", "answer": "Multiple sclerosis (MS) is an autoimmune disease where the immune system attacks the protective covering of nerves, causing communication problems between the brain and the rest of the body."},
    {"question": "What are the early signs of Alzheimer's disease?", "answer": "Early signs of Alzheimer's include memory loss, confusion, difficulty completing familiar tasks, and changes in mood or personality."},
    {"question": "What is a TIA?", "answer": "A transient ischemic attack (TIA) is a temporary period of symptoms similar to those of a stroke, often called a mini-stroke, and is a warning sign of future strokes."},
    {"question": "What is neuropathy?", "answer": "Neuropathy refers to damage or dysfunction of one or more nerves, resulting in numbness, tingling, muscle weakness, and pain in the affected area."},
    {"question": "What is Bell's palsy?", "answer": "Bell's palsy is a sudden weakness or paralysis of the muscles on one side of the face, usually temporary and often linked to viral infections."},
    {"question": "What is ALS?", "answer": "Amyotrophic lateral sclerosis (ALS) is a progressive neurodegenerative disease that affects nerve cells in the brain and spinal cord, leading to muscle weakness and atrophy."},
    {"question": "What is a seizure?", "answer": "A seizure is a sudden, uncontrolled electrical disturbance in the brain that can cause changes in behavior, movements, feelings, or consciousness."},
    {"question": "What is a concussion?", "answer": "A concussion is a mild traumatic brain injury caused by a blow or jolt to the head, leading to temporary loss of normal brain function."},
    {"question": "What is dementia?", "answer": "Dementia is a general term for a decline in cognitive function severe enough to interfere with daily life, often seen in Alzheimer's disease."},
    {"question": "What is a brain tumor?", "answer": "A brain tumor is an abnormal growth of cells within the brain, which can be benign or malignant and may cause neurological symptoms."},
    {"question": "What is carpal tunnel syndrome?", "answer": "Carpal tunnel syndrome is a condition caused by compression of the median nerve in the wrist, leading to numbness, tingling, and weakness in the hand."},
    {"question": "What is Guillain-Barré syndrome?", "answer": "Guillain-Barré syndrome is a rare disorder where the body's immune system attacks the nerves, causing muscle weakness and sometimes paralysis."},
    {"question": "What is myasthenia gravis?", "answer": "Myasthenia gravis is a chronic autoimmune disorder that causes weakness in the skeletal muscles responsible for breathing and moving parts of the body."},
    {"question": "What is trigeminal neuralgia?", "answer": "Trigeminal neuralgia is a chronic pain condition affecting the trigeminal nerve in the face, causing extreme, sporadic facial pain."},
    {"question": "What is hydrocephalus?", "answer": "Hydrocephalus is a condition characterized by an accumulation of cerebrospinal fluid within the brain, leading to increased pressure inside the skull."},
    {"question": "What is an aneurysm?", "answer": "An aneurysm is a bulge or ballooning in a blood vessel in the brain, which can leak or rupture, causing bleeding in the brain (hemorrhagic stroke)."},
    {"question": "What is a lumbar puncture?", "answer": "A lumbar puncture (spinal tap) is a procedure to collect cerebrospinal fluid from the lower back for diagnostic testing."},
    {"question": "What is a CT scan?", "answer": "A CT scan (computed tomography) is an imaging procedure that uses X-rays to create detailed pictures of the brain and other parts of the body."},
    {"question": "What is an MRI?", "answer": "An MRI (magnetic resonance imaging) uses magnetic fields and radio waves to create detailed images of the brain and spinal cord."},
    {"question": "What is an EEG?", "answer": "An EEG (electroencephalogram) is a test that measures electrical activity in the brain and is often used to diagnose epilepsy and other brain disorders."},
    {"question": "What is a nerve conduction study?", "answer": "A nerve conduction study measures how quickly electrical signals move through your nerves and is used to diagnose nerve damage or dysfunction."},
    {"question": "What is a movement disorder?", "answer": "A movement disorder is a group of neurological conditions that cause abnormal voluntary or involuntary movements, such as tremors or tics."},
    {"question": "What is dystonia?", "answer": "Dystonia is a movement disorder characterized by involuntary muscle contractions that cause repetitive or twisting movements."},
    {"question": "What is ataxia?", "answer": "Ataxia refers to a lack of muscle coordination that can affect speech, eye movements, and the ability to swallow, walk, or pick up objects."},
    {"question": "What is a cluster headache?", "answer": "A cluster headache is a severe headache that occurs in cyclical patterns or clusters, often around one eye."},
    {"question": "What is a tension headache?", "answer": "A tension headache is a common type of headache characterized by a constant, dull pain on both sides of the head."},
    {"question": "What is neuralgia?", "answer": "Neuralgia is intense, typically intermittent pain along the course of a nerve, especially in the head or face."},
    {"question": "What is a spinal cord injury?", "answer": "A spinal cord injury is damage to the spinal cord that can result in loss of function, such as mobility or feeling."},
    {"question": "What is peripheral neuropathy?", "answer": "Peripheral neuropathy is a result of damage to the nerves outside the brain and spinal cord, often causing weakness, numbness, and pain."},
    {"question": "What is a neurodegenerative disease?", "answer": "A neurodegenerative disease is a condition that involves the progressive loss of structure or function of neurons, such as Alzheimer's or Parkinson's disease."},
    {"question": "What is a cranial nerve?", "answer": "Cranial nerves are twelve pairs of nerves that emerge directly from the brain and control sensory and motor functions of the head and neck."},
    {"question": "What is a synapse?", "answer": "A synapse is the junction between two nerve cells, where electrical or chemical signals are transmitted."},
    {"question": "What is a neurotransmitter?", "answer": "A neurotransmitter is a chemical messenger that transmits signals across a synapse from one neuron to another."},
    {"question": "What is a myelin sheath?", "answer": "The myelin sheath is a protective covering that surrounds nerve fibers and helps increase the speed of electrical impulses."},
    {"question": "What is a reflex?", "answer": "A reflex is an involuntary and nearly instantaneous movement in response to a stimulus."},
    {"question": "What is a coma?", "answer": "A coma is a deep state of prolonged unconsciousness in which a person cannot be awakened and does not respond to stimuli."},
    {"question": "What is encephalitis?", "answer": "Encephalitis is inflammation of the brain, usually caused by a viral infection."},
    {"question": "What is meningitis?", "answer": "Meningitis is inflammation of the membranes (meninges) surrounding the brain and spinal cord, often due to infection."},
    {"question": "What is a brain abscess?", "answer": "A brain abscess is a collection of pus that develops in response to an infection or trauma in the brain."},
    {"question": "What is a transient global amnesia?", "answer": "Transient global amnesia is a sudden, temporary episode of memory loss that can't be attributed to a more common neurological condition."},
    {"question": "What is narcolepsy?", "answer": "Narcolepsy is a chronic sleep disorder characterized by overwhelming daytime drowsiness and sudden attacks of sleep."},
    {"question": "What is restless legs syndrome?", "answer": "Restless legs syndrome is a condition characterized by an uncontrollable urge to move the legs, usually due to uncomfortable sensations."},
    {"question": "What is sleep apnea?", "answer": "Sleep apnea is a sleep disorder in which breathing repeatedly stops and starts during sleep."},
    {"question": "What is a neuropsychological test?", "answer": "A neuropsychological test is a structured task or paper-and-pencil test used to assess a person's cognitive, motor, behavioral, and linguistic abilities."},
    {"question": "What is a lumbar disc herniation?", "answer": "A lumbar disc herniation occurs when the soft center of a spinal disc pushes through a crack in the tougher exterior casing, often causing pain or numbness."},
    {"question": "What is radiculopathy?", "answer": "Radiculopathy is a condition caused by compression, inflammation, or injury to a spinal nerve root, resulting in pain, numbness, or weakness."},
    {"question": "What is a tremor?", "answer": "A tremor is an involuntary, rhythmic muscle contraction leading to shaking movements in one or more parts of the body."},
    {"question": "What is spasticity?", "answer": "Spasticity is a condition in which certain muscles are continuously contracted, causing stiffness or tightness of the muscles."},
    {"question": "What is a neurotoxin?", "answer": "A neurotoxin is a substance that is poisonous or destructive to nerve tissue."},
    {"question": "What is a PET scan?", "answer": "A PET scan (positron emission tomography) is an imaging test that helps reveal how your tissues and organs are functioning."},
    {"question": "What is a functional MRI?", "answer": "A functional MRI (fMRI) measures and maps the brain's activity by detecting changes associated with blood flow."},
    {"question": "What is a nerve block?", "answer": "A nerve block is an injection of medication that blocks pain from specific nerves or a group of nerves."},
    {"question": "What is a shunt?", "answer": "A shunt is a tube that is surgically placed to drain excess fluid from the brain to another part of the body."},
    {"question": "What is a neuroblastoma?", "answer": "Neuroblastoma is a type of cancer that forms in certain types of nerve tissue, most often in the adrenal glands."},
    {"question": "What is a glioblastoma?", "answer": "Glioblastoma is an aggressive type of cancer that can occur in the brain or spinal cord."},
    {"question": "What is a meningioma?", "answer": "A meningioma is a tumor that forms on membranes covering the brain and spinal cord just inside the skull."},
    {"question": "What is a pituitary tumor?", "answer": "A pituitary tumor is an abnormal growth in the pituitary gland, which can affect hormone levels in the body."},
    {"question": "What is a neurofibroma?", "answer": "A neurofibroma is a benign nerve sheath tumor in the peripheral nervous system."},
    {"question": "What is a schwannoma?", "answer": "A schwannoma is a tumor of the tissue that covers nerves, called the nerve sheath."},
    {"question": "What is a subdural hematoma?", "answer": "A subdural hematoma is a collection of blood outside the brain, usually caused by severe head injuries."},
    {"question": "What is a subarachnoid hemorrhage?", "answer": "A subarachnoid hemorrhage is bleeding in the space between the brain and the tissue covering the brain, often from a ruptured aneurysm."},
    {"question": "What is a cerebral palsy?", "answer": "Cerebral palsy is a group of disorders that affect movement and muscle tone or posture, caused by damage that occurs to the immature brain as it develops."},
    {"question": "What is a neurocutaneous syndrome?", "answer": "Neurocutaneous syndromes are a group of rare neurological lifelong disorders that lead to tumors growing in various parts of the body."},
    {"question": "What is a neuroimmunology?", "answer": "Neuroimmunology is the study of the interaction between the nervous system and the immune system."},
    {"question": "What is a neurogenetics?", "answer": "Neurogenetics is the study of the role of genetics in the development and function of the nervous system."},
    {"question": "What is a neuro-ophthalmology?", "answer": "Neuro-ophthalmology is a subspecialty that merges the fields of neurology and ophthalmology, often dealing with visual problems related to the nervous system."},
    {"question": "What is a neuropsychology?", "answer": "Neuropsychology is the study of the relationship between brain function and behavior."},
    {"question": "What is a neurorehabilitation?", "answer": "Neurorehabilitation is a complex medical process aimed at aiding recovery from a nervous system injury and minimizing and/or compensating for any functional alterations resulting from it."},
    {"question": "What is a neurocritical care?", "answer": "Neurocritical care is a medical field that treats life-threatening diseases of the nervous system and identifies, prevents/treats secondary brain injury."},
    {"question": "What is a neurovascular disease?", "answer": "Neurovascular diseases are disorders that affect the blood vessels of the brain and spinal cord."},
    {"question": "What is a neuroendocrine tumor?", "answer": "A neuroendocrine tumor is a type of tumor that arises from cells of the endocrine (hormonal) and nervous systems."},
    {"question": "What is a neuroinflammation?", "answer": "Neuroinflammation is inflammation of the nervous tissue, which may be initiated in response to a variety of cues."},
    {"question": "What is a neuroplasticity?", "answer": "Neuroplasticity is the ability of the brain to form and reorganize synaptic connections, especially in response to learning or experience or following injury."},
    {"question": "What is a neurotrophic factor?", "answer": "A neurotrophic factor is a family of biomolecules that support the growth, survival, and differentiation of both developing and mature neurons."},
    {"question": "What is a neuropeptide?", "answer": "A neuropeptide is a small protein-like molecule used by neurons to communicate with each other."},
    {"question": "What is a neuroleptic?", "answer": "A neuroleptic is a class of medication used to manage psychosis, principally in schizophrenia and bipolar disorder."},
    {"question": "What is a neuromodulation?", "answer": "Neuromodulation is the alteration of nerve activity through targeted delivery of a stimulus, such as electrical stimulation or chemical agents."},
    {"question": "What is a neurosurgery?", "answer": "Neurosurgery is the medical specialty concerned with the prevention, diagnosis, surgical treatment, and rehabilitation of disorders which affect any portion of the nervous system."},
    {"question": "What is a neuroanatomy?", "answer": "Neuroanatomy is the study of the structure and organization of the nervous system."},
    {"question": "What is a neurophysiology?", "answer": "Neurophysiology is the study of the function of the nervous system."},
    {"question": "What is a neuropharmacology?", "answer": "Neuropharmacology is the study of how drugs affect cellular function in the nervous system."},
    {"question": "What is a neuroethics?", "answer": "Neuroethics is the study of the ethical, legal, and social implications of neuroscience."},
    {"question": "What is a neuroepidemiology?", "answer": "Neuroepidemiology is the study of the distribution and determinants of neurological disorders in populations."},
    {"question": "What is a neurovirology?", "answer": "Neurovirology is the study of viruses that infect the nervous system."},
    {"question": "What is a neurooncology?", "answer": "Neurooncology is the study of brain and spinal cord neoplasms, many of which are very dangerous and life-threatening."},
    {"question": "What is a neurotrauma?", "answer": "Neurotrauma refers to injuries to the nervous system, especially the brain and spinal cord."},
    {"question": "What is a neurodevelopmental disorder?", "answer": "A neurodevelopmental disorder is a disorder of brain function that affects emotion, learning ability, self-control, and memory and that unfolds as the individual grows."},
    {"question": "What is a neurocutaneous disorder?", "answer": "Neurocutaneous disorders are a group of rare neurological lifelong disorders that lead to tumors growing in various parts of the body."},
    {"question": "What is a neurogenesis?", "answer": "Neurogenesis is the process by which new neurons are formed in the brain."},
    {"question": "What is a neuroimaging?", "answer": "Neuroimaging includes the use of various techniques to either directly or indirectly image the structure, function, or pharmacology of the nervous system."},
    {"question": "What is a neuropeptide?", "answer": "A neuropeptide is a small protein-like molecule used by neurons to communicate with each other."},
    {"question": "What is a neuromuscular disease?", "answer": "A neuromuscular disease is a disorder that affects the peripheral nervous system, including muscles, nerves, and the neuromuscular junction."},
    {"question": "What is a neuropsychological assessment?", "answer": "A neuropsychological assessment is a comprehensive evaluation of cognitive, behavioral, and emotional functioning using a set of standardized tests and procedures."},
    {"question": "What is a neurostimulation?", "answer": "Neurostimulation is the purposeful modulation of the nervous system's activity using invasive or non-invasive means."},
    {"question": "What is a neurovascular intervention?", "answer": "A neurovascular intervention is a minimally invasive procedure to treat blood vessel disorders in the brain and spinal cord."},
    {"question": "What is a neurotology?", "answer": "Neurotology is a subspecialty of otolaryngology (ENT) that focuses on diseases of the inner ear and skull base."},
    {"question": "What is a neurometabolic disorder?", "answer": "A neurometabolic disorder is a genetic disorder that affects how the body uses food and energy, often impacting the nervous system."},
    {"question": "What is a neurosarcoidosis?", "answer": "Neurosarcoidosis is a form of sarcoidosis that affects the nervous system."},
    {"question": "What is a neuroacanthocytosis?", "answer": "Neuroacanthocytosis is a group of rare inherited neurodegenerative disorders characterized by movement problems and misshapen red blood cells."},
    {"question": "What is a neurolinguistics?", "answer": "Neurolinguistics is the study of the neural mechanisms in the human brain that control the comprehension, production, and acquisition of language."},
    {"question": "What is a neurogenetic disorder?", "answer": "A neurogenetic disorder is a disorder caused by changes in the genes or chromosomes that affect the nervous system."},
    {"question": "What is a neurofibromatosis?", "answer": "Neurofibromatosis is a genetic disorder that causes tumors to form on nerve tissue."},
    {"question": "What is a neuromonitoring?", "answer": "Neuromonitoring is the use of specialized techniques to monitor the function of the nervous system during surgery."},
    {"question": "What is a neuropeptide Y?", "answer": "Neuropeptide Y is a peptide that is involved in various physiological and homeostatic processes in the brain and body."},
    {"question": "What is a neuroblast?", "answer": "A neuroblast is an embryonic cell from which nerve fibers originate."},
    {"question": "What is a neurocytoma?", "answer": "A neurocytoma is a rare, typically benign brain tumor that arises from neuronal cells."},
    {"question": "What is a neurosyphilis?", "answer": "Neurosyphilis is an infection of the brain or spinal cord caused by the bacterium Treponema pallidum."},
    {"question": "What is a neuroleptic malignant syndrome?", "answer": "Neuroleptic malignant syndrome is a life-threatening reaction to antipsychotic drugs characterized by fever, muscle rigidity, and altered mental status."},
    {"question": "What is a neurotmesis?", "answer": "Neurotmesis is the most severe type of nerve injury in which both the nerve and the nerve sheath are disrupted."},
    {"question": "What is a neuroma?", "answer": "A neuroma is a growth or tumor of nerve tissue."},
    {"question": "What is a neurosarcoidosis?", "answer": "Neurosarcoidosis is a form of sarcoidosis that affects the nervous system."},
    {"question": "What is a neurolytic block?", "answer": "A neurolytic block is a procedure that uses chemicals or heat to destroy nerves and relieve pain."},
    {"question": "What is a neurogenic bladder?", "answer": "A neurogenic bladder is a condition in which a person lacks bladder control due to a brain, spinal cord, or nerve problem."},
    {"question": "What is a neurogenic claudication?", "answer": "Neurogenic claudication is pain caused by nerve compression in the lower spine, often due to spinal stenosis."},
    {"question": "What is a neurogenic shock?", "answer": "Neurogenic shock is a type of distributive shock resulting in low blood pressure, occasionally with a slowed heart rate, attributed to the disruption of the autonomic pathways within the spinal cord."},
    {"question": "What is a neurohypophysis?", "answer": "The neurohypophysis is the posterior part of the pituitary gland, which releases hormones produced by the hypothalamus."},
    {"question": "What is a neuromuscular junction?", "answer": "A neuromuscular junction is a chemical synapse formed by the contact between a motor neuron and a muscle fiber."},
    {"question": "What is a neurosphere?", "answer": "A neurosphere is a culture system composed of free-floating clusters of neural stem cells."},
    {"question": "What is a neurotensin?", "answer": "Neurotensin is a neuropeptide that acts as a neurotransmitter and neuromodulator in the brain."},
    {"question": "What is a neuropeptide S?", "answer": "Neuropeptide S is a peptide that regulates arousal, anxiety, and sleep in the brain."},
    {"question": "What is a neuropeptide B?", "answer": "Neuropeptide B is a peptide involved in the regulation of feeding and energy homeostasis."},
    {"question": "What is a neuropeptide FF?", "answer": "Neuropeptide FF is a peptide that modulates pain and opioid tolerance in the nervous system."},
    {"question": "What is a neuropeptide W?", "answer": "Neuropeptide W is a peptide that plays a role in the regulation of feeding and energy metabolism."},
    {"question": "What is a neuropeptide Y receptor?", "answer": "A neuropeptide Y receptor is a protein that binds neuropeptide Y and mediates its effects in the body."},
    {"question": "What is a neuropeptide S receptor?", "answer": "A neuropeptide S receptor is a protein that binds neuropeptide S and mediates its effects in the body."},
    {"question": "What is a neuropeptide B receptor?", "answer": "A neuropeptide B receptor is a protein that binds neuropeptide B and mediates its effects in the body."},
    {"question": "What is a neuropeptide FF receptor?", "answer": "A neuropeptide FF receptor is a protein that binds neuropeptide FF and mediates its effects in the body."},
    {"question": "What is a neuropeptide W receptor?", "answer": "A neuropeptide W receptor is a protein that binds neuropeptide W and mediates its effects in the body."}
] 