NEUROLOGY_QA = [
    {"question": "What is a migraine?", "answer": "A migraine is a type of headache characterized by intense, throbbing pain, often accompanied by nausea, vomiting, and sensitivity to light or sound."},
    {"question": "What are the symptoms of a stroke?", "answer": "Symptoms of a stroke include sudden numbness or weakness, confusion, trouble speaking, vision problems, dizziness, and loss of balance or coordination."},
    {"question": "What is epilepsy?", "answer": "Epilepsy is a neurological disorder marked by recurrent, unprovoked seizures due to abnormal electrical activity in the brain."},
    {"question": "What causes Parkinson's disease?", "answer": "Parkinson's disease is caused by the degeneration of dopamine-producing neurons in the brain, leading to movement and coordination problems."},
    {"question": "What is multiple sclerosis?", "answer": "Multiple sclerosis (MS) is an autoimmune disease where the immune system attacks the protective covering of nerves, causing communication problems between the brain and the rest of the body."},
    {"question": "What are the early signs of Alzheimer's disease?", "answer": "Early signs of Alzheimer's include memory loss, confusion, difficulty completing familiar tasks, and changes in mood or personality."},
    {"question": "What is a TIA?", "answer": "A transient ischemic attack (TIA) is a temporary period of symptoms similar to those of a stroke, often called a mini-stroke, and is a warning sign of future strokes."},
    {"question": "What is neuropathy?", "answer": "Neuropathy refers to damage or dysfunction of one or more nerves, resulting in numbness, tingling, muscle weakness, and pain in the affected area."},
    {"question": "What is Bell's palsy?", "answer": "Bell's palsy is a sudden weakness or paralysis of the muscles on one side of the face, usually temporary and often linked to viral infections."},
    {"question": "What is ALS?", "answer": "Amyotrophic lateral sclerosis (ALS) is a progressive neurodegenerative disease that affects nerve cells in the brain and spinal cord, leading to muscle weakness and atrophy."},
    {"question": "What is a seizure?", "answer": "A seizure is a sudden, uncontrolled electrical disturbance in the brain that can cause changes in behavior, movements, feelings, or consciousness."},
    {"question": "What is a concussion?", "answer": "A concussion is a mild traumatic brain injury caused by a blow or jolt to the head, leading to temporary loss of normal brain function."},
    {"question": "What is dementia?", "answer": "Dementia is a general term for a decline in cognitive function severe enough to interfere with daily life, often seen in Alzheimer's disease."},
    {"question": "What is a brain tumor?", "answer": "A brain tumor is an abnormal growth of cells within the brain, which can be benign or malignant and may cause neurological symptoms."},
    {"question": "What is carpal tunnel syndrome?", "answer": "Carpal tunnel syndrome is a condition caused by compression of the median nerve in the wrist, leading to numbness, tingling, and weakness in the hand."},
    {"question": "What is Guillain-Barré syndrome?", "answer": "Guillain-Barré syndrome is a rare disorder where the body's immune system attacks the nerves, causing muscle weakness and sometimes paralysis."},
    {"question": "What is myasthenia gravis?", "answer": "Myasthenia gravis is a chronic autoimmune disorder that causes weakness in the skeletal muscles responsible for breathing and moving parts of the body."},
    {"question": "What is trigeminal neuralgia?", "answer": "Trigeminal neuralgia is a chronic pain condition affecting the trigeminal nerve in the face, causing extreme, sporadic facial pain."},
    {"question": "What is hydrocephalus?", "answer": "Hydrocephalus is a condition characterized by an accumulation of cerebrospinal fluid within the brain, leading to increased pressure inside the skull."},
    {"question": "What is an aneurysm?", "answer": "An aneurysm is a bulge or ballooning in a blood vessel in the brain, which can leak or rupture, causing bleeding in the brain (hemorrhagic stroke)."},
    {"question": "What is a lumbar puncture?", "answer": "A lumbar puncture (spinal tap) is a procedure to collect cerebrospinal fluid from the lower back for diagnostic testing."},
    {"question": "What is a CT scan?", "answer": "A CT scan (computed tomography) is an imaging procedure that uses X-rays to create detailed pictures of the brain and other parts of the body."},
    {"question": "What is an MRI?", "answer": "An MRI (magnetic resonance imaging) uses magnetic fields and radio waves to create detailed images of the brain and spinal cord."},
    {"question": "What is an EEG?", "answer": "An EEG (electroencephalogram) is a test that measures electrical activity in the brain and is often used to diagnose epilepsy and other brain disorders."},
    {"question": "What is a nerve conduction study?", "answer": "A nerve conduction study measures how quickly electrical signals move through your nerves and is used to diagnose nerve damage or dysfunction."},
    {"question": "What is a movement disorder?", "answer": "A movement disorder is a group of neurological conditions that cause abnormal voluntary or involuntary movements, such as tremors or tics."},
    {"question": "What is dystonia?", "answer": "Dystonia is a movement disorder characterized by involuntary muscle contractions that cause repetitive or twisting movements."},
    {"question": "What is ataxia?", "answer": "Ataxia refers to a lack of muscle coordination that can affect speech, eye movements, and the ability to swallow, walk, or pick up objects."},
    {"question": "What is a cluster headache?", "answer": "A cluster headache is a severe headache that occurs in cyclical patterns or clusters, often around one eye."},
    {"question": "What is a tension headache?", "answer": "A tension headache is a common type of headache characterized by a constant, dull pain on both sides of the head."},
    {"question": "What is neuralgia?", "answer": "Neuralgia is intense, typically intermittent pain along the course of a nerve, especially in the head or face."},
    {"question": "What is a spinal cord injury?", "answer": "A spinal cord injury is damage to the spinal cord that can result in loss of function, such as mobility or feeling."},
    {"question": "What is peripheral neuropathy?", "answer": "Peripheral neuropathy is a result of damage to the nerves outside the brain and spinal cord, often causing weakness, numbness, and pain."},
    {"question": "What is a neurodegenerative disease?", "answer": "A neurodegenerative disease is a condition that involves the progressive loss of structure or function of neurons, such as Alzheimer's or Parkinson's disease."},
    {"question": "What is a cranial nerve?", "answer": "Cranial nerves are twelve pairs of nerves that emerge directly from the brain and control sensory and motor functions of the head and neck."},
    {"question": "What is a synapse?", "answer": "A synapse is the junction between two nerve cells, where electrical or chemical signals are transmitted."},
    {"question": "What is a neurotransmitter?", "answer": "A neurotransmitter is a chemical messenger that transmits signals across a synapse from one neuron to another."},
    {"question": "What is a myelin sheath?", "answer": "The myelin sheath is a protective covering that surrounds nerve fibers and helps increase the speed of electrical impulses."},
    {"question": "What is a reflex?", "answer": "A reflex is an involuntary and nearly instantaneous movement in response to a stimulus."},
    {"question": "What is a coma?", "answer": "A coma is a deep state of prolonged unconsciousness in which a person cannot be awakened and does not respond to stimuli."},
    {"question": "What is encephalitis?", "answer": "Encephalitis is inflammation of the brain, usually caused by a viral infection."},
    {"question": "What is meningitis?", "answer": "Meningitis is inflammation of the membranes (meninges) surrounding the brain and spinal cord, often due to infection."},
    {"question": "What is a brain abscess?", "answer": "A brain abscess is a collection of pus that develops in response to an infection or trauma in the brain."},
    {"question": "What is a transient global amnesia?", "answer": "Transient global amnesia is a sudden, temporary episode of memory loss that can't be attributed to a more common neurological condition."},
    {"question": "What is narcolepsy?", "answer": "Narcolepsy is a chronic sleep disorder characterized by overwhelming daytime drowsiness and sudden attacks of sleep."},
    {"question": "What is restless legs syndrome?", "answer": "Restless legs syndrome is a condition characterized by an uncontrollable urge to move the legs, usually due to uncomfortable sensations."},
    {"question": "What is sleep apnea?", "answer": "Sleep apnea is a sleep disorder in which breathing repeatedly stops and starts during sleep."},
    {"question": "What is a neuropsychological test?", "answer": "A neuropsychological test is a structured task or paper-and-pencil test used to assess a person's cognitive, motor, behavioral, and linguistic abilities."},
    {"question": "What is a lumbar disc herniation?", "answer": "A lumbar disc herniation occurs when the soft center of a spinal disc pushes through a crack in the tougher exterior casing, often causing pain or numbness."},
    {"question": "What is radiculopathy?", "answer": "Radiculopathy is a condition caused by compression, inflammation, or injury to a spinal nerve root, resulting in pain, numbness, or weakness."},
    {"question": "What is a tremor?", "answer": "A tremor is an involuntary, rhythmic muscle contraction leading to shaking movements in one or more parts of the body."},
    {"question": "What is spasticity?", "answer": "Spasticity is a condition in which certain muscles are continuously contracted, causing stiffness or tightness of the muscles."},
    {"question": "What is a neurotoxin?", "answer": "A neurotoxin is a substance that is poisonous or destructive to nerve tissue."},
    {"question": "What is a PET scan?", "answer": "A PET scan (positron emission tomography) is an imaging test that helps reveal how your tissues and organs are functioning."},
    {"question": "What is a functional MRI?", "answer": "A functional MRI (fMRI) measures and maps the brain's activity by detecting changes associated with blood flow."},
    {"question": "What is a nerve block?", "answer": "A nerve block is an injection of medication that blocks pain from specific nerves or a group of nerves."},
    {"question": "What is a shunt?", "answer": "A shunt is a tube that is surgically placed to drain excess fluid from the brain to another part of the body."},
    {"question": "What is a neuroblastoma?", "answer": "Neuroblastoma is a type of cancer that forms in certain types of nerve tissue, most often in the adrenal glands."},
    {"question": "What is a glioblastoma?", "answer": "Glioblastoma is an aggressive type of cancer that can occur in the brain or spinal cord."},
    {"question": "What is a meningioma?", "answer": "A meningioma is a tumor that forms on membranes covering the brain and spinal cord just inside the skull."},
    {"question": "What is a pituitary tumor?", "answer": "A pituitary tumor is an abnormal growth in the pituitary gland, which can affect hormone levels in the body."},
    {"question": "What is a neurofibroma?", "answer": "A neurofibroma is a benign nerve sheath tumor in the peripheral nervous system."},
    {"question": "What is a schwannoma?", "answer": "A schwannoma is a tumor of the tissue that covers nerves, called the nerve sheath."},
    {"question": "What is a subdural hematoma?", "answer": "A subdural hematoma is a collection of blood outside the brain, usually caused by severe head injuries."},
    {"question": "What is a subarachnoid hemorrhage?", "answer": "A subarachnoid hemorrhage is bleeding in the space between the brain and the tissue covering the brain, often from a ruptured aneurysm."},
    {"question": "What is a cerebral palsy?", "answer": "Cerebral palsy is a group of disorders that affect movement and muscle tone or posture, caused by damage that occurs to the immature brain as it develops."},
    {"question": "What is a neurocutaneous syndrome?", "answer": "Neurocutaneous syndromes are a group of rare neurological lifelong disorders that lead to tumors growing in various parts of the body."},
    {"question": "What is a neuroimmunology?", "answer": "Neuroimmunology is the study of the interaction between the nervous system and the immune system."},
    {"question": "What is a neurogenetics?", "answer": "Neurogenetics is the study of the role of genetics in the development and function of the nervous system."},
    {"question": "What is a neuro-ophthalmology?", "answer": "Neuro-ophthalmology is a subspecialty that merges the fields of neurology and ophthalmology, often dealing with visual problems related to the nervous system."},
    {"question": "What is a neuropsychology?", "answer": "Neuropsychology is the study of the relationship between brain function and behavior."},
    {"question": "What is a neurorehabilitation?", "answer": "Neurorehabilitation is a complex medical process aimed at aiding recovery from a nervous system injury and minimizing and/or compensating for any functional alterations resulting from it."},
    {"question": "What is a neurocritical care?", "answer": "Neurocritical care is a medical field that treats life-threatening diseases of the nervous system and identifies, prevents/treats secondary brain injury."},
    {"question": "What is a neurovascular disease?", "answer": "Neurovascular diseases are disorders that affect the blood vessels of the brain and spinal cord."},
    {"question": "What is a neuroendocrine tumor?", "answer": "A neuroendocrine tumor is a type of tumor that arises from cells of the endocrine (hormonal) and nervous systems."},
    {"question": "What is a neuroinflammation?", "answer": "Neuroinflammation is inflammation of the nervous tissue, which may be initiated in response to a variety of cues."},
    {"question": "What is a neuroplasticity?", "answer": "Neuroplasticity is the ability of the brain to form and reorganize synaptic connections, especially in response to learning or experience or following injury."},
    {"question": "What is a neurotrophic factor?", "answer": "A neurotrophic factor is a family of biomolecules that support the growth, survival, and differentiation of both developing and mature neurons."},
    {"question": "What is a neuropeptide?", "answer": "A neuropeptide is a small protein-like molecule used by neurons to communicate with each other."},
    {"question": "What is a neuroleptic?", "answer": "A neuroleptic is a class of medication used to manage psychosis, principally in schizophrenia and bipolar disorder."},
    {"question": "What is a neuromodulation?", "answer": "Neuromodulation is the alteration of nerve activity through targeted delivery of a stimulus, such as electrical stimulation or chemical agents."},
    {"question": "What is a neurosurgery?", "answer": "Neurosurgery is the medical specialty concerned with the prevention, diagnosis, surgical treatment, and rehabilitation of disorders which affect any portion of the nervous system."},
    {"question": "What is a neuroanatomy?", "answer": "Neuroanatomy is the study of the structure and organization of the nervous system."},
    {"question": "What is a neurophysiology?", "answer": "Neurophysiology is the study of the function of the nervous system."},
    {"question": "What is a neuropharmacology?", "answer": "Neuropharmacology is the study of how drugs affect cellular function in the nervous system."},
    {"question": "What is a neuroethics?", "answer": "Neuroethics is the study of the ethical, legal, and social implications of neuroscience."},
    {"question": "What is a neuroepidemiology?", "answer": "Neuroepidemiology is the study of the distribution and determinants of neurological disorders in populations."},
    {"question": "What is a neurovirology?", "answer": "Neurovirology is the study of viruses that infect the nervous system."},
    {"question": "What is a neurooncology?", "answer": "Neurooncology is the study of brain and spinal cord neoplasms, many of which are very dangerous and life-threatening."},
    {"question": "What is a neurotrauma?", "answer": "Neurotrauma refers to injuries to the nervous system, especially the brain and spinal cord."},
    {"question": "What is a neurodevelopmental disorder?", "answer": "A neurodevelopmental disorder is a disorder of brain function that affects emotion, learning ability, self-control, and memory and that unfolds as the individual grows."},
    {"question": "What is a neurocutaneous disorder?", "answer": "Neurocutaneous disorders are a group of rare neurological lifelong disorders that lead to tumors growing in various parts of the body."},
    {"question": "What is a neurogenesis?", "answer": "Neurogenesis is the process by which new neurons are formed in the brain."},
    {"question": "What is a neuroimaging?", "answer": "Neuroimaging includes the use of various techniques to either directly or indirectly image the structure, function, or pharmacology of the nervous system."},
    {"question": "What is a neuropeptide?", "answer": "A neuropeptide is a small protein-like molecule used by neurons to communicate with each other."},
    {"question": "What is a neuromuscular disease?", "answer": "A neuromuscular disease is a disorder that affects the peripheral nervous system, including muscles, nerves, and the neuromuscular junction."},
    {"question": "What is a neuropsychological assessment?", "answer": "A neuropsychological assessment is a comprehensive evaluation of cognitive, behavioral, and emotional functioning using a set of standardized tests and procedures."},
    {"question": "What is a neurostimulation?", "answer": "Neurostimulation is the purposeful modulation of the nervous system's activity using invasive or non-invasive means."},
    {"question": "What is a neurovascular intervention?", "answer": "A neurovascular intervention is a minimally invasive procedure to treat blood vessel disorders in the brain and spinal cord."},
    {"question": "What is a neurotology?", "answer": "Neurotology is a subspecialty of otolaryngology (ENT) that focuses on diseases of the inner ear and skull base."},
    {"question": "What is a neurometabolic disorder?", "answer": "A neurometabolic disorder is a genetic disorder that affects how the body uses food and energy, often impacting the nervous system."},
    {"question": "What is a neurosarcoidosis?", "answer": "Neurosarcoidosis is a form of sarcoidosis that affects the nervous system."},
    {"question": "What is a neuroacanthocytosis?", "answer": "Neuroacanthocytosis is a group of rare inherited neurodegenerative disorders characterized by movement problems and misshapen red blood cells."},
    {"question": "What is a neurolinguistics?", "answer": "Neurolinguistics is the study of the neural mechanisms in the human brain that control the comprehension, production, and acquisition of language."},
    {"question": "What is a neurogenetic disorder?", "answer": "A neurogenetic disorder is a disorder caused by changes in the genes or chromosomes that affect the nervous system."},
    {"question": "What is a neurofibromatosis?", "answer": "Neurofibromatosis is a genetic disorder that causes tumors to form on nerve tissue."},
    {"question": "What is a neuromonitoring?", "answer": "Neuromonitoring is the use of specialized techniques to monitor the function of the nervous system during surgery."},
    {"question": "What is a neuropeptide Y?", "answer": "Neuropeptide Y is a peptide that is involved in various physiological and homeostatic processes in the brain and body."},
    {"question": "What is a neuroblast?", "answer": "A neuroblast is an embryonic cell from which nerve fibers originate."},
    {"question": "What is a neurocytoma?", "answer": "A neurocytoma is a rare, typically benign brain tumor that arises from neuronal cells."},
    {"question": "What is a neurosyphilis?", "answer": "Neurosyphilis is an infection of the brain or spinal cord caused by the bacterium Treponema pallidum."},
    {"question": "What is a neuroleptic malignant syndrome?", "answer": "Neuroleptic malignant syndrome is a life-threatening reaction to antipsychotic drugs characterized by fever, muscle rigidity, and altered mental status."},
    {"question": "What is a neurotmesis?", "answer": "Neurotmesis is the most severe type of nerve injury in which both the nerve and the nerve sheath are disrupted."},
    {"question": "What is a neuroma?", "answer": "A neuroma is a growth or tumor of nerve tissue."},
    {"question": "What is a neurosarcoidosis?", "answer": "Neurosarcoidosis is a form of sarcoidosis that affects the nervous system."},
    {"question": "What is a neurolytic block?", "answer": "A neurolytic block is a procedure that uses chemicals or heat to destroy nerves and relieve pain."},
    {"question": "What is a neurogenic bladder?", "answer": "A neurogenic bladder is a condition in which a person lacks bladder control due to a brain, spinal cord, or nerve problem."},
    {"question": "What is a neurogenic claudication?", "answer": "Neurogenic claudication is pain caused by nerve compression in the lower spine, often due to spinal stenosis."},
    {"question": "What is a neurogenic shock?", "answer": "Neurogenic shock is a type of distributive shock resulting in low blood pressure, occasionally with a slowed heart rate, attributed to the disruption of the autonomic pathways within the spinal cord."},
    {"question": "What is a neurohypophysis?", "answer": "The neurohypophysis is the posterior part of the pituitary gland, which releases hormones produced by the hypothalamus."},
    {"question": "What is a neuromuscular junction?", "answer": "A neuromuscular junction is a chemical synapse formed by the contact between a motor neuron and a muscle fiber."},
    {"question": "What is a neurosphere?", "answer": "A neurosphere is a culture system composed of free-floating clusters of neural stem cells."},
    {"question": "What is a neurotensin?", "answer": "Neurotensin is a neuropeptide that acts as a neurotransmitter and neuromodulator in the brain."},
    {"question": "What is a neuropeptide S?", "answer": "Neuropeptide S is a peptide that regulates arousal, anxiety, and sleep in the brain."},
    {"question": "What is a neuropeptide B?", "answer": "Neuropeptide B is a peptide involved in the regulation of feeding and energy homeostasis."},
    {"question": "What is a neuropeptide FF?", "answer": "Neuropeptide FF is a peptide that modulates pain and opioid tolerance in the nervous system."},
    {"question": "What is a neuropeptide W?", "answer": "Neuropeptide W is a peptide that plays a role in the regulation of feeding and energy metabolism."},
    {"question": "What is a neuropeptide Y receptor?", "answer": "A neuropeptide Y receptor is a protein that binds neuropeptide Y and mediates its effects in the body."},
    {"question": "What is a neuropeptide S receptor?", "answer": "A neuropeptide S receptor is a protein that binds neuropeptide S and mediates its effects in the body."},
    {"question": "What is a neuropeptide B receptor?", "answer": "A neuropeptide B receptor is a protein that binds neuropeptide B and mediates its effects in the body."},
    {"question": "What is a neuropeptide FF receptor?", "answer": "A neuropeptide FF receptor is a protein that binds neuropeptide FF and mediates its effects in the body."},
    {"question": "What is a neuropeptide W receptor?", "answer": "A neuropeptide W receptor is a protein that binds neuropeptide W and mediates its effects in the body."},
    {"question": "What is a cranial nerve?", "answer": "Cranial nerves are 12 pairs of nerves that originate directly from the brain and control sensory and motor functions in the head, neck, and some parts of the body."},
    {"question": "What is multiple sclerosis?", "answer": "Multiple sclerosis (MS) is an autoimmune disease affecting the central nervous system, where the immune system attacks the protective covering of nerve fibers."},
    {"question": "What is Parkinson’s disease?", "answer": "Parkinson’s disease is a progressive neurological disorder characterized by tremors, stiffness, and difficulty with balance and coordination due to loss of dopamine-producing brain cells."},
    {"question": "What is Alzheimer’s disease?", "answer": "Alzheimer’s disease is a progressive neurodegenerative disorder that leads to memory loss, cognitive decline, and eventually loss of bodily function."},
    {"question": "What is epilepsy?", "answer": "Epilepsy is a neurological disorder characterized by recurrent seizures caused by abnormal electrical activity in the brain."},
    {"question": "What is a seizure?", "answer": "A seizure is a sudden surge of electrical activity in the brain that can cause changes in behavior, movement, or consciousness."},
    {"question": "What is a stroke?", "answer": "A stroke occurs when blood flow to part of the brain is interrupted, leading to brain cell death and potential long-term disability."},
    {"question": "What is a transient ischemic attack (TIA)?", "answer": "A TIA is a temporary disruption of blood flow to the brain that causes stroke-like symptoms but usually does not result in permanent damage."},
    {"question": "What is meningitis?", "answer": "Meningitis is an inflammation of the membranes surrounding the brain and spinal cord, often caused by infection."},
    {"question": "What is encephalitis?", "answer": "Encephalitis is an inflammation of the brain tissue, typically caused by viral infections or autoimmune responses."},
    {"question": "What is Bell’s palsy?", "answer": "Bell’s palsy is a condition that causes sudden weakness or paralysis on one side of the face due to dysfunction of the facial nerve."},
    {"question": "What is Guillain-Barré syndrome?", "answer": "Guillain-Barré syndrome is a rare autoimmune disorder where the immune system attacks the peripheral nerves, causing muscle weakness and sometimes paralysis."},
    {"question": "What is myasthenia gravis?", "answer": "Myasthenia gravis is a chronic autoimmune neuromuscular disease that causes weakness in skeletal muscles, particularly those controlling eye and eyelid movement, facial expression, and swallowing."},
    {"question": "What is amyotrophic lateral sclerosis (ALS)?", "answer": "ALS is a progressive neurodegenerative disease that affects nerve cells in the brain and spinal cord, leading to loss of muscle control."},
    {"question": "What is Huntington’s disease?", "answer": "Huntington’s disease is a genetic disorder that causes progressive breakdown of nerve cells in the brain, leading to movement disorders and cognitive decline."},
    {"question": "What is Tourette syndrome?", "answer": "Tourette syndrome is a neurological disorder characterized by repetitive, involuntary movements and vocalizations called tics."},
    {"question": "What is cerebral palsy?", "answer": "Cerebral palsy is a group of disorders that affect movement and muscle tone or posture, caused by damage to the developing brain before or shortly after birth."},
    {"question": "What is migraine?", "answer": "A migraine is a type of headache that often causes severe pain, nausea, and sensitivity to light and sound."},
    {"question": "What is vertigo?", "answer": "Vertigo is a sensation of spinning or dizziness caused by problems in the inner ear or brain."},
    {"question": "What is hydrocephalus?", "answer": "Hydrocephalus is a buildup of cerebrospinal fluid in the brain that can lead to increased pressure inside the skull."},
    {"question": "What is a concussion?", "answer": "A concussion is a mild traumatic brain injury caused by a blow to the head or violent shaking, resulting in temporary brain dysfunction."},
    {"question": "What is a brain tumor?", "answer": "A brain tumor is an abnormal growth of cells within the brain, which can be benign or malignant."},
    {"question": "What is a lumbar puncture?", "answer": "A lumbar puncture (or spinal tap) is a medical procedure used to collect cerebrospinal fluid for diagnostic testing or to administer medications."},
    {"question": "What is aphasia?", "answer": "Aphasia is a language disorder caused by damage to the brain, such as from a stroke, that affects the ability to speak, understand language, read, or write."},
    {"question": "What is apraxia?", "answer": "Apraxia is a neurological disorder characterized by the inability to perform learned, purposeful movements despite having the desire and physical ability to do so."},
    {"question": "What is agnosia?", "answer": "Agnosia is the inability to process sensory information normally, such as recognizing objects, sounds, or smells, despite intact senses."},
    {"question": "What is dysarthria?", "answer": "Dysarthria is a speech disorder caused by muscle weakness, often due to neurological damage, that affects articulation and clarity of speech."},
    {"question": "What is bradykinesia?", "answer": "Bradykinesia refers to slowness of movement and is a common symptom of Parkinson’s disease."},
    {"question": "What is akinesia?", "answer": "Akinesia is the absence or loss of voluntary movement, often seen in advanced Parkinson’s disease."},
    {"question": "What is chorea?", "answer": "Chorea is a movement disorder involving brief, irregular contractions that are not rhythmic and often appear dance-like, commonly seen in Huntington’s disease."},
    {"question": "What is hemiplegia?", "answer": "Hemiplegia is paralysis on one side of the body, often caused by brain injury or stroke."},
    {"question": "What is paraplegia?", "answer": "Paraplegia is the loss of movement and sensation in both legs, typically caused by spinal cord injury."},
    {"question": "What is quadriplegia?", "answer": "Quadriplegia is the loss of movement and sensation in all four limbs, usually due to injury to the cervical spinal cord."},
    {"question": "What is spasticity?", "answer": "Spasticity is a condition in which certain muscles are continuously contracted, causing stiffness and tightness, often seen in cerebral palsy or MS."},
    {"question": "What is neuropathy?", "answer": "Neuropathy refers to nerve damage that often causes pain, numbness, tingling, or weakness, typically in the hands and feet."},
    {"question": "What is autonomic dysfunction?", "answer": "Autonomic dysfunction is a disorder of the autonomic nervous system that can affect heart rate, blood pressure, digestion, and other automatic bodily functions."},
    {"question": "What is syncope?", "answer": "Syncope is the medical term for fainting, which is a temporary loss of consciousness usually related to insufficient blood flow to the brain."},
    {"question": "What is coma?", "answer": "A coma is a prolonged state of unconsciousness in which a person cannot be awakened and shows no signs of awareness."},
    {"question": "What is locked-in syndrome?", "answer": "Locked-in syndrome is a rare neurological condition in which a patient is conscious but unable to move or communicate verbally due to complete paralysis of nearly all voluntary muscles."},
    {"question": "What is a neurologist?", "answer": "A neurologist is a doctor who specializes in diagnosing and treating disorders of the nervous system, including the brain, spinal cord, and peripheral nerves."},
    {"question": "What is a neurosurgeon?", "answer": "A neurosurgeon is a surgeon who specializes in treating conditions of the nervous system, including the brain, spine, and peripheral nerves, using surgical methods."},
    {"question": "What is a neuropsychologist?", "answer": "A neuropsychologist is a psychologist who studies how the brain and its structures relate to specific psychological processes and behaviors, often working with patients with brain injuries or neurological diseases."},
    {"question": "What is a neurophysiologist?", "answer": "A neurophysiologist is a specialist who studies the function of the nervous system, especially the electrical properties of neurons, and may conduct tests like EEGs or EMGs."},
    {"question": "What is a neuroradiologist?", "answer": "A neuroradiologist is a radiologist who interprets imaging studies of the brain, spinal cord, and nervous system, such as MRI and CT scans."},
    {"question": "What is a neuro ICU?", "answer": "A neuro ICU (neurological intensive care unit) is a specialized hospital unit for critically ill patients with neurological conditions like stroke, brain trauma, or severe infections."},
    {"question": "What is a neurorehabilitation program?", "answer": "A neurorehabilitation program is a treatment plan designed to help patients recover from neurological injuries or diseases through therapies like physical therapy, occupational therapy, and speech therapy."},
    {"question": "What is a neurostimulator?", "answer": "A neurostimulator is a device implanted in the body to deliver electrical impulses to specific nerves or areas of the brain to treat conditions like chronic pain, Parkinson’s disease, or epilepsy."},
    {"question": "What is deep brain stimulation (DBS)?", "answer": "Deep brain stimulation is a surgical treatment involving the implantation of a neurostimulator that sends electrical signals to specific areas of the brain to reduce symptoms of movement disorders like Parkinson’s disease."},
    {"question": "What is electromyography (EMG)?", "answer": "EMG is a diagnostic test that measures the electrical activity of muscles at rest and during contraction to detect neuromuscular abnormalities."},
    {"question": "What is a visual evoked potential (VEP)?", "answer": "A VEP is a test that measures the brain’s response to visual stimuli and is used to assess optic nerve function, often in diagnosing multiple sclerosis."},
    {"question": "What is a brainstem auditory evoked potential (BAEP)?", "answer": "BAEP is a test that evaluates hearing pathways in the brainstem and helps diagnose auditory nerve issues or multiple sclerosis."},
    {"question": "What is somatosensory evoked potential (SSEP)?", "answer": "SSEP is a test that measures the brain’s response to sensory stimuli applied to the limbs and is used to evaluate the function of sensory pathways in the nervous system."},
    {"question": "What is a PET scan?", "answer": "A PET scan (positron emission tomography) uses radioactive tracers to create images of organs and tissues, helping to visualize brain activity or detect tumors."},
    {"question": "What is a SPECT scan?", "answer": "A SPECT scan is a nuclear imaging test that uses a radioactive substance and a special camera to create 3D images of blood flow to tissues and organs, including the brain."},
    {"question": "What is lumbar disc herniation?", "answer": "Lumbar disc herniation is a condition in which the soft material inside a spinal disc protrudes through the outer layer, potentially compressing nearby nerves and causing pain."},
    {"question": "What is sciatica?", "answer": "Sciatica is a condition characterized by pain radiating along the path of the sciatic nerve, usually due to compression of the nerve roots in the lower back."},
    {"question": "What is carpal tunnel syndrome?", "answer": "Carpal tunnel syndrome is a condition caused by compression of the median nerve as it passes through the wrist, leading to numbness, tingling, and weakness in the hand."},
    {"question": "What is trigeminal neuralgia?", "answer": "Trigeminal neuralgia is a chronic pain condition that affects the trigeminal nerve, causing episodes of intense facial pain."},
    {"question": "What is radiculopathy?", "answer": "Radiculopathy refers to a set of conditions caused by compression, inflammation, or injury to a spinal nerve root, often causing pain, numbness, or weakness along the nerve’s path."},
    {"question": "What is cauda equina syndrome?", "answer": "Cauda equina syndrome is a serious neurological condition caused by compression of the bundle of nerve roots at the lower end of the spinal cord, requiring urgent treatment."},
    {"question": "What is a Chiari malformation?", "answer": "Chiari malformation is a structural defect in the cerebellum where brain tissue extends into the spinal canal, potentially causing neurological symptoms."},
    {"question": "What is syringomyelia?", "answer": "Syringomyelia is a rare disorder characterized by the formation of fluid-filled cysts within the spinal cord, which can cause pain, weakness, and stiffness."},
    {"question": "What is restless legs syndrome?", "answer": "Restless legs syndrome is a neurological disorder that causes uncomfortable sensations in the legs and an irresistible urge to move them, often worsening at night."},
    {"question": "What is narcolepsy?", "answer": "Narcolepsy is a sleep disorder that involves excessive daytime sleepiness and sudden attacks of sleep, often accompanied by cataplexy or hallucinations."},
    {"question": "What is REM sleep behavior disorder?", "answer": "REM sleep behavior disorder is a condition in which people physically act out their dreams during REM sleep, often due to neurological conditions like Parkinson’s disease."},
    {"question": "What is essential tremor?", "answer": "Essential tremor is a neurological disorder that causes involuntary, rhythmic shaking, most commonly in the hands, and can worsen with age."},
    {"question": "What is dystonia?", "answer": "Dystonia is a movement disorder characterized by sustained or repetitive muscle contractions, resulting in twisting movements or abnormal postures."},
    {"question": "What is blepharospasm?", "answer": "Blepharospasm is a form of dystonia involving the eyelids, causing frequent blinking or forced closure of the eyes."},
    {"question": "What is cervical dystonia?", "answer": "Cervical dystonia, also known as spasmodic torticollis, is a type of dystonia that affects the neck muscles, causing the head to twist or turn involuntarily."},
    {"question": "What is botulinum toxin used for in neurology?", "answer": "Botulinum toxin (commonly known as Botox) is used in neurology to treat conditions like dystonia, spasticity, migraines, and overactive bladder by temporarily relaxing overactive muscles."},
    {"question": "What is status epilepticus?", "answer": "Status epilepticus is a medical emergency in which a seizure lasts longer than five minutes or seizures occur in succession without regaining consciousness between them."},
    {"question": "What is Lennox-Gastaut syndrome?", "answer": "Lennox-Gastaut syndrome is a severe form of epilepsy that begins in childhood and is characterized by multiple types of seizures and intellectual disability."},
    {"question": "What is Dravet syndrome?", "answer": "Dravet syndrome is a rare, drug-resistant form of epilepsy that begins in infancy and is associated with prolonged seizures and developmental delays."},
    {"question": "What is neuroplasticity?", "answer": "Neuroplasticity is the brain’s ability to reorganize itself by forming new neural connections, allowing recovery and adaptation after injury or learning new skills."},
    {"question": "What is a neurocognitive disorder?", "answer": "A neurocognitive disorder is a condition involving impaired mental functions such as memory, attention, and judgment, often due to neurological disease or injury."},
    {"question": "What is frontotemporal dementia?", "answer": "Frontotemporal dementia is a group of disorders caused by progressive nerve cell loss in the brain’s frontal or temporal lobes, leading to changes in personality, behavior, and language."},
    {"question": "What is Creutzfeldt-Jakob disease?", "answer": "Creutzfeldt-Jakob disease is a rare, rapidly progressive, and fatal brain disorder caused by abnormal proteins called prions."},
    {"question": "What is normal pressure hydrocephalus?", "answer": "Normal pressure hydrocephalus is a type of hydrocephalus that occurs in older adults and is characterized by gait disturbances, urinary incontinence, and cognitive decline."},
    {"question": "What is Wada test?", "answer": "The Wada test is a procedure used to determine which hemisphere of the brain controls language and memory, often before epilepsy surgery."},
    {"question": "What is a ketogenic diet?", "answer": "A ketogenic diet is a high-fat, low-carbohydrate diet used primarily to treat difficult-to-control epilepsy, especially in children."},
    {"question": "What is vagus nerve stimulation?", "answer": "Vagus nerve stimulation is a treatment for epilepsy and depression that involves delivering electrical impulses to the vagus nerve via an implanted device."},
    {"question": "What is transcranial magnetic stimulation (TMS)?", "answer": "TMS is a noninvasive procedure that uses magnetic fields to stimulate nerve cells in the brain and is used to treat depression and some neurological disorders."},
    {"question": "What is functional neurological disorder (FND)?", "answer": "Functional neurological disorder is a condition where there is a problem with the functioning of the nervous system and how the brain and body send and receive signals, despite no structural disease being present."},
    {"question": "What is astrology?", "answer": "Astrology is the study of the movements and relative positions of celestial bodies interpreted as having an influence on human affairs and the natural world."},
    {"question": "How many zodiac signs are there?", "answer": "There are 12 zodiac signs: Aries, Taurus, Gemini, Cancer, Leo, Virgo, Libra, Scorpio, Sagittarius, Capricorn, Aquarius, and Pisces."},
    {"question": "What is a sun sign?", "answer": "Your sun sign represents your core personality, ego, and general behavior. It's determined by the position of the Sun at the time of your birth."},
    {"question": "What is a moon sign?", "answer": "Your moon sign represents your emotional nature, inner self, and how you process feelings. It’s based on the Moon’s position at your birth."},
    {"question": "What is a rising sign (ascendant)?", "answer": "Your rising sign is the zodiac sign that was on the eastern horizon at the moment of your birth. It influences your appearance and how others perceive you."},
    {"question": "What is a birth chart?", "answer": "A birth chart (or natal chart) is a map of the sky showing the exact positions of the planets at the time and place of your birth."},
    {"question": "What are the elements in astrology?", "answer": "The four elements in astrology are Fire, Earth, Air, and Water. Each zodiac sign belongs to one of these elements."},
    {"question": "Which zodiac signs are fire signs?", "answer": "The fire signs are Aries, Leo, and Sagittarius."},
    {"question": "Which zodiac signs are earth signs?", "answer": "The earth signs are Taurus, Virgo, and Capricorn."},
    {"question": "Which zodiac signs are air signs?", "answer": "The air signs are Gemini, Libra, and Aquarius."},
    {"question": "Which zodiac signs are water signs?", "answer": "The water signs are Cancer, Scorpio, and Pisces."},
    {"question": "What are planetary aspects?", "answer": "Planetary aspects are angles formed between planets in a chart that describe how the planets interact with each other."},
    {"question": "What is Mercury retrograde?", "answer": "Mercury retrograde is when the planet Mercury appears to move backward in the sky, often associated with communication issues, delays, and technological glitches."},
    {"question": "What is Venus retrograde?", "answer": "Venus retrograde occurs every 18 months and affects love, relationships, finances, and personal values."},
    {"question": "What is Mars retrograde?", "answer": "Mars retrograde happens approximately every two years and can affect energy levels, motivation, and physical activity."},
    {"question": "What are the 12 houses in astrology?", "answer": "The 12 astrological houses represent different areas of life such as self, money, communication, home, creativity, health, relationships, transformation, travel, career, friendships, and spirituality."},
    {"question": "What is the first house?", "answer": "The first house governs self-image, the body, and how you present yourself to the world."},
    {"question": "What is the second house?", "answer": "The second house relates to personal finances, possessions, and values."},
    {"question": "What is the third house?", "answer": "The third house governs communication, siblings, short trips, and early education."},
    {"question": "What is the fourth house?", "answer": "The fourth house is associated with home, family, roots, and emotional foundations."},
    {"question": "What is the fifth house?", "answer": "The fifth house rules creativity, romance, children, and self-expression."},
    {"question": "What is the sixth house?", "answer": "The sixth house deals with health, daily routines, work, and service to others."},
    {"question": "What is the seventh house?", "answer": "The seventh house is about partnerships, marriage, and one-on-one relationships."},
    {"question": "What is the eighth house?", "answer": "The eighth house governs shared resources, intimacy, death, rebirth, and transformation."},
    {"question": "What is the ninth house?", "answer": "The ninth house relates to higher learning, philosophy, foreign travel, and spirituality."},
    {"question": "What is the tenth house?", "answer": "The tenth house rules career, public image, and long-term goals."},
    {"question": "What is the eleventh house?", "answer": "The eleventh house is associated with friendships, hopes, wishes, and community."},
    {"question": "What is the twelfth house?", "answer": "The twelfth house governs hidden matters, subconscious patterns, secrets, and spiritual retreat."},
    {"question": "What is a conjunction in astrology?", "answer": "A conjunction is when two planets are close together in the same sign, blending their energies and intensifying their effects."},
    {"question": "What is a square aspect?", "answer": "A square is a challenging aspect of 90 degrees between two planets, indicating tension, conflict, and obstacles."},
    {"question": "What is a trine aspect?", "answer": "A trine is a harmonious 120-degree angle between planets, representing ease, flow, and opportunities."},
    {"question": "What is an opposition aspect?", "answer": "An opposition occurs when two planets are 180 degrees apart, symbolizing duality, balance, and challenges in relationships."},
    {"question": "What is a sextile aspect?", "answer": "A sextile is a 60-degree aspect that indicates potential, opportunity, and support from others."},
    {"question": "What is a quincunx aspect?", "answer": "A quincunx is a 150-degree aspect that brings adjustment, discomfort, and the need for adaptation."},
    {"question": "What is a grand trine?", "answer": "A grand trine is a triangle formed by three planets in trine aspect, bringing harmony and natural talent but sometimes complacency."},
    {"question": "What is a T-square?", "answer": "A T-square is a configuration involving two planets in opposition and a third forming squares to both, creating tension and drive."},
    {"question": "What is a stellium?", "answer": "A stellium occurs when three or more planets are clustered in the same sign or house, intensifying the focus on that area of life."},
    {"question": "What is synastry?", "answer": "Synastry is the comparison of two birth charts to assess compatibility between individuals in relationships."},
    {"question": "What is composite astrology?", "answer": "Composite astrology creates a new chart based on the midpoint between two people's planets, used to analyze relationship dynamics."},
    {"question": "What is a progressed chart?", "answer": "A progressed chart moves the planets forward in the birth chart by one day per year to reflect personal growth and evolving life themes."},
    {"question": "What is solar arc progression?", "answer": "Solar arc progression involves advancing each planet by the number of degrees the Sun has moved over the years, offering insights into major life transitions."},
    {"question": "What is a solar return chart?", "answer": "A solar return chart is cast for the moment the Sun returns to its natal position each year, used to predict themes for the upcoming year."},
    {"question": "What is lunar phase interpretation?", "answer": "Lunar phase interpretation considers the phase of the Moon at birth (new, full, crescent, etc.) to understand personal cycles and emotional patterns."},
    {"question": "What is the North Node?", "answer": "The North Node (or True Node) represents your soul’s karmic direction and life purpose in this lifetime."},
    {"question": "What is the South Node?", "answer": "The South Node reflects past-life tendencies, habits, and behaviors that may no longer serve you in this life."},
    {"question": "What is a fixed star in astrology?", "answer": "Fixed stars are non-moving stars like Sirius or Spica that have specific energetic influences when aligned with planets in a chart."},
    {"question": "What is Lilith?", "answer": "Lilith represents the dark feminine energy, independence, and repressed desires. It's often associated with shadow traits and power struggles."},
    {"question": "What is the Vertex?", "answer": "The Vertex is a sensitive point in the chart associated with fated encounters and significant relationships."},
    {"question": "What is the Part of Fortune?", "answer": "The Part of Fortune is a mathematical point calculated from the positions of the Sun, Moon, and Ascendant, linked to prosperity and well-being."},
    {"question": "What is Chiron?", "answer": "Chiron, known as the 'wounded healer,' represents our deepest wounds and our ability to heal ourselves and others."},
    {"question": "What are asteroids in astrology?", "answer": "Asteroids like Ceres, Juno, Pallas Athena, and Vesta are minor celestial bodies that add depth to interpretations, especially in relationships and personal growth."},
    {"question": "What is mundane astrology?", "answer": "Mundane astrology studies world events, natural disasters, and political trends through planetary movements."},
    {"question": "What is electional astrology?", "answer": "Electional astrology selects favorable times to begin activities based on planetary alignments."},
    {"question": "What is horary astrology?", "answer": "Horary astrology answers specific questions by interpreting a chart cast for the exact moment the question is asked."},
    {"question": "What is medical astrology?", "answer": "Medical astrology links parts of the body and diseases to zodiac signs, planets, and houses."},
    {"question": "What is financial astrology?", "answer": "Financial astrology uses planetary cycles to predict market trends and economic shifts."},
    {"question": "What is predictive astrology?", "answer": "Predictive astrology uses transits, progressions, and other techniques to forecast future events and life phases."},
    {"question": "What is the role of the Moon in astrology?", "answer": "The Moon represents emotions, instincts, needs, and the subconscious mind. It changes signs every 2–3 days."},
    {"question": "What is the role of the Sun in astrology?", "answer": "The Sun represents the conscious self, identity, vitality, and core essence. It stays in each sign for about a month."},
    {"question": "What is the role of Mercury in astrology?", "answer": "Mercury governs communication, thinking style, learning, and how we express ideas."},
    {"question": "What is the role of Venus in astrology?", "answer": "Venus rules love, relationships, beauty, pleasure, and financial values."},
    {"question": "What is the role of Mars in astrology?", "answer": "Mars represents action, desire, aggression, sexuality, and how we pursue goals."},
    {"question": "What is the role of Jupiter in astrology?", "answer": "Jupiter signifies expansion, growth, luck, higher learning, and philosophical outlook."},
    {"question": "What is the role of Saturn in astrology?", "answer": "Saturn governs discipline, responsibility, structure, limitations, and lessons learned through effort."},
    {"question": "What is the role of Uranus in astrology?", "answer": "Uranus represents innovation, rebellion, sudden change, and individuality."},
    {"question": "What is the role of Neptune in astrology?", "answer": "Neptune rules dreams, illusions, spirituality, creativity, and confusion."},
    {"question": "What is the role of Pluto in astrology?", "answer": "Pluto is associated with transformation, power, deep psychological processes, and rebirth."},
    {"question": "What is the significance of the Midheaven (MC)?", "answer": "The Midheaven is the highest point in the birth chart and represents career, public reputation, and life direction."},
    {"question": "What is the Imum Coeli (IC)?", "answer": "The Imum Coeli is the lowest point in the chart and represents home, family, roots, and private life."},
    {"question": "What is the Descendant?", "answer": "The Descendant is the cusp of the seventh house and represents partnerships and how we relate to others."},
    {"question": "What is the Ascendant?", "answer": "The Ascendant, or rising sign, marks the beginning of the first house and determines how we appear to the world and approach life."},
    {"question": "What is a Grand Cross?", "answer": "A Grand Cross consists of four planets forming squares to each other, creating intense pressure and challenges requiring resolution."},
    {"question": "What is a Yod?", "answer": "A Yod, or Finger of God, is formed when two planets form a sextile and both quincunx a third, indicating a unique life mission or challenge."},
    {"question": "What is a Mystic Rectangle?", "answer": "A Mystic Rectangle consists of two oppositions connected by trines and sextiles, bringing harmony, opportunities, and balance."},
    {"question": "What is a Kite formation?", "answer": "A Kite includes a grand trine and an opposition connected by sextiles, providing potential for achievement and creative use of talents."},
    {"question": "What is a Taurus season?", "answer": "Taurus season runs from approximately April 20 to May 20 and is associated with stability, sensuality, and material comfort."},
    {"question": "What is Gemini season?", "answer": "Gemini season runs from approximately May 21 to June 20 and is associated with communication, curiosity, and social interaction."},
    {"question": "What is Cancer season?", "answer": "Cancer season runs from approximately June 21 to July 22 and focuses on emotion, home, and nurturing."},
    {"question": "What is Leo season?", "answer": "Leo season runs from approximately July 23 to August 22 and is associated with confidence, creativity, and self-expression."},
    {"question": "What is Virgo season?", "answer": "Virgo season runs from approximately August 23 to September 22 and emphasizes organization, analysis, and practicality."},
    {"question": "What is Libra season?", "answer": "Libra season runs from approximately September 23 to October 22 and focuses on relationships, diplomacy, and aesthetics."},
    {"question": "What is Scorpio season?", "answer": "Scorpio season runs from approximately October 23 to November 21 and is associated with intensity, mystery, and transformation."},
    {"question": "What is Sagittarius season?", "answer": "Sagittarius season runs from approximately November 22 to December 21 and is linked to adventure, philosophy, and freedom."},
    {"question": "What is Capricorn season?", "answer": "Capricorn season runs from approximately December 22 to January 19 and focuses on ambition, structure, and discipline."},
    {"question": "What is Aquarius season?", "answer": "Aquarius season runs from approximately January 20 to February 18 and emphasizes innovation, independence, and humanitarianism."},
    {"question": "What is Pisces season?", "answer": "Pisces season runs from approximately February 19 to March 20 and is associated with intuition, imagination, and compassion."},
    {"question": "What is Aries season?", "answer": "Aries season runs from approximately March 21 to April 19 and is associated with action, courage, and initiation."}
    


] 
